services:
  nats-server-imc:
    image: nats:latest
    ports:
      - 8223:8223
      - 8224:8224

  # auth-db:
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #   container_name: auth-db

  # imc-db:
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  #   ports:
  #     - '5434:5432'
  #   environment:
  #     - POSTGRES_PASSWORD=M1S3Cr37P4s5w0rd
  #     - POSTGRES_DB=ImcDB
  #   container_name: imc-db

  localstack-imc:
    image: localstack/localstack
    container_name: localstackImc
    environment:
      - SERVICES=secretsmanager,ssm
    ports:
      - '4566:4566'
      - '4571:4571'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
